### ISSUE TITLE
Remount script parameters

### ISSUE THREAD

**Issue by jjvelar** [aivus/synology-dsm-scripts#1]
Hi, first let me thank you for sharing these scripts. Much appreciated.

My USB external drive is shown as usb1 and usbshare1.

I have tried several combinations (example: 1-1 & 1-1 /volumeUSB1/usbshare1) but unable to remount after ejecting the USB drive.

Get this error message: "Directory /volumeUSB1/usb1 does not exist. Remount HDD" (that changes depending the combination of parameters I use)

Here is the outcome of "ls -l /sys/bus/usb/devices/*/product", "ls -l /sys/bus/usb/devices/", and "cat /sys/bus/usb/devices/1-1/product".

Would appreciate any suggestion to make remount script work.

Thanks in advance for your help.

![image](https://github.com/aivus/synology-dsm-scripts/assets/47498098/5fa5f9f2-8d8f-4ed9-9f12-1415816f2bce)

![image](https://github.com/aivus/synology-dsm-scripts/assets/47498098/34a46cfc-b64a-4621-9cbc-a81dc5f6fad1)

![image](https://github.com/aivus/synology-dsm-scripts/assets/47498098/0d36a7f5-5efd-4587-8a27-8ea8e1cff3e7)

**Comment by aivus** [comment]
Hello @jjvelar 

Try to run `cat /sys/bus/usb/devices/*/product` and see where is your device.

Regarding the second parameter, run `df -h | grep USB` after you insert external drive to see the path for the mounted directories.It should return something like:
```
$ df -h | grep USB
/dev/sdq1       197M   14K  197M   1% /volumeUSB2/usbshare2-1
/dev/sdq2       932G  433G  500G  47% /volumeUSB2/usbshare2-2
```

**Comment by jjvelar** [comment]
Thanks for your reply.

"cat /sys/bus/usb/devices/*/product" returns

![image](https://github.com/aivus/synology-dsm-scripts/assets/47498098/0aea32a5-941e-492d-aa04-04002b8fb7c8)

And "df -h | grep USB" returns

![image](https://github.com/aivus/synology-dsm-scripts/assets/47498098/d49a7af9-100a-43e0-8f6b-e92497ed26f9)

I unmounted the USB drive and tried "/volume1/scripts/remount.sh USBDevice /volumeUSB1/usbshare".

Got error "Directory /volumeUSB1/usbshare exists. No need to remount HDD, Skipping..."

What else should I try?

Thanks!

**Comment by aivus** [comment]
It should be `/volume1/scripts/remount.sh 4-2 /volumeUSB1/usbshare` for you.

**Comment by aivus** [comment]
You need to eject the disk using the DSM UI (do not disconnect physically) before using the script to remount it

**Comment by jjvelar** [comment]
Thanks again for your fast reply.

I tried "/volume1/scripts/remount.sh 4-2 /volumeUSB1/usbshare" but still getting the error message "Directory /volumeUSB1/usbshare exists. No need to remount HDD, Skipping..."

Didn't eject the disk; just succesfully executed your "eject" script: "/volume1/scripts/eject.sh usb1"

**Comment by aivus** [comment]
After you run eject script, wait ~10 seconds. Ejecting may take such time.

Then check output of `df -h | grep USB`. It shouldn't return mounted devices.

Message `Directory /volumeUSB1/usbshare exists. No need to remount HDD, Skipping...` means that the directory for the USB disk exists an no remounting is needed (as it's already mounted)

**Comment by jjvelar** [comment]
Hi,

I run the eject script with parameter "usb1", waited for 10 seconds, run df -h | grep USB and got nothing, as expected:

![image](https://github.com/aivus/synology-dsm-scripts/assets/47498098/42571ef1-c18c-4c86-a7f7-96101765e141)

I also verifyed in Control Panel -> External Devices, and there is no external USB device available, as expected:

![image](https://github.com/aivus/synology-dsm-scripts/assets/47498098/7f997673-141d-4e21-a0ff-05b3102d3fbb)

Then run the mount script again with "4-2" and "/volumeUSB1/usbshare" as parameters, and got the same error message again:

"Directory /volumeUSB1/usbshare exists. No need to remount HDD, Skipping..."

I am lost here...

**Comment by aivus** [comment]
After some version, DSM stopped removing directory after the unmounting.
Call `rm -d /volumeUSB2/usbshare` right **before** `remount.sh` call.
This command will remove directory _only_ in case it's empty. Which is the case when it's not mounted

I'll consider improving the script later

**Comment by jjvelar** [comment]
I have executed this piece of code including the "rm" call:

```
#!/bin/bash
rm -d /volumeUSB1/usbshare
sleep 1
/volume1/scripts/remount.sh 4-2 /volumeUSB1/usbshare
```
And got this error: "Directory /volumeUSB1/usbshare does not exist. Remount HDD"

Also tried with "/volumeUSB2/usbshare" and got the error:

"rm: cannot remove '/volumeUSB2/usbshare': No such file or directory
Directory /volumeUSB2/usbshare does not exist. Remount HDD"

**Comment by aivus** [comment]
> Directory /volumeUSB2/usbshare does not exist. Remount HDD"

After this disk should appear in DSM within 10-15 seconds.

Please double-check `volumeUSB1` and `volumeUSB2`. It's mixed in your last response.

**Comment by jjvelar** [comment]
Thanks again for replying. I am afraid it doesn’t show up.
Tried both: volumeUSB1 and volumeUSB2. No success.

**Comment by jjvelar** [comment]
Hi,

Tried everything again paying attention to some delays but it didn't work.

These are the steps I have followed:

1) Executed the eject script witn "usb1" as parameter:

`
/volume1/scripts/eject.sh usb1
`

2) Result was successful ("Unmount USB device usb1 succeeded.") and after a few seconds, USB drive was ejected.

3) Waited for a minute or so and executed the remount script with your suggested parameters "4-2" and "/volumeUSB1/usbshare" with the "rm -d" call with "/volumeUSB1/usbshare" as parameter:

```
rm -d /volumeUSB1/usbshare
sleep 5
/volume1/scripts/remount.sh 4-2 /volumeUSB1/usbshare
```
4) Waited for a couple of minutes but it failed as the USB drive was not available and got the error message "Directory /volumeUSB1/usbshare does not exist. Remount HDD"

5) The only way to have the USB drive available again is to unplug and plug it again.

Is there anything else I can try?

**Comment by aivus** [comment]
> got the error message "Directory /volumeUSB1/usbshare does not exist. Remount HDD"

It's not an error, but script is notifying that it's remounting the disk.

Could you please try to use `4-1` instead of `4-2`?

**Comment by jjvelar** [comment]
> > got the error message "Directory /volumeUSB1/usbshare does not exist. Remount HDD"
> 
> It's not an error, but script is notifying that it's remounting the disk.
> 
> Could you please try to use `4-1` instead of `4-2`?

It worked!
Thanks a lot for your support. Much appreciated.
